name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Remove binary files from history
        run: |
          git filter-branch --index-filter '
            git rm --cached --ignore-unmatch screenshots/ai_news.png
            git rm --cached --ignore-unmatch screenshots/basic_chatbot.png
            git rm --cached --ignore-unmatch screenshots/chatbot_with_search_tool.png
            git rm --cached --ignore-unmatch screenshots/customer_support.png
            git rm --cached --ignore-unmatch screenshots/travel_planner.png
          ' --prune-empty --tag-name-filter cat -- --all

      - name: Push cleaned history to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://genaitiwari:${HF_TOKEN}@huggingface.co/spaces/genaitiwari/langgraphagenticaitiwari
          git push --force origin main
